Feat/define domain entities
dyoshyy/CurlARC-Service pull request #4
Opened 2024-05-10 03:12 UTC by dyoshyy

## やったこと
user, record, teamのentityを実装した。
## できるようになったこと

## 動作確認手順
直接ファイルを見てください
## 確認してほしいこと
不足している情報がないか確認してください

2024-05-10 05:16 UTC, g-ohara requested changes
`internal/domain/record.go` にいくつか気になった点をコメント

2024-05-10 05:16 UTC, genji1024 commented on internal/domain/record.go
> +	StonesCoordinate []StoneCoordinate // 全ストーンの位置
ストーンの位置は各ショット後に変化するので，`StonesCoordinate` は `Shot` の属性としたほうがよい

2024-05-10 05:16 UTC, genji1024 commented on internal/domain/record.go
> +type StoneCoordinate struct {
ストーンは有効エリアから出ると取り除かれるので，
- `StoneCoordinate` にストーンが有効か無効かに関する属性を追加
- `StonesCoordinate` を `Shot` の属性に変更 (該当部分のコメント参照) したうえで，無効なストーンは `StonesCoordinate` から取り除く

のいずれかで対応したほうがよい

2024-05-10 05:16 UTC, g-ohara commented on internal/domain/record.go
> +	StoneNumber int
`StoneNumber` は両チームのストーンの通し番号？
<ol start="0">
  <li>先攻の1投目</li>
  <li>後攻の1投目</li>
  <li>先攻の2投目</li>
  <li>．．．</li>
</ol>

これでもどちらのチームのストーンかを取得することはできるが，それが面倒なら `Team` 属性を追加してもよい

2024-05-10 05:16 UTC, g-ohara commented on internal/domain/record.go
> +	Shot             Shot
1エンドあたり16投 (各チーム8投) あるので，`Shot` ではなく `[]Shot`

2024-05-10 05:16 UTC, g-ohara commented on internal/domain/record.go
> +	Score            int // エンド終了時の得点
エンド終了時の得点はストーンの位置から一意に定まるので，`Score` 属性は冗長かも

2024-05-12 04:10 UTC, dyoshyy commented on internal/domain/record.go
> +	Score            int // エンド終了時の得点
一旦ここは可読性のためにScore属性をもたせとく。あとから要らなくなったら消すわ

2024-05-12 06:13 UTC, g-ohara commented
LGTM

2024-05-12 10:04 UTC, merged