feat: add entry `is_red` to `Record`
dyoshyy/CurlARC-Service pull request #42
Opened 2024-12-30 10:22 UTC by g-ohara

## やったこと

- `is_red` を`Record` のエントリーとして追加

## できるようになったこと

- 自チームのストーンの色の管理

## 動作確認手順

- https://github.com/g-ohara/CurlARC-Web/pull/56 と合わせて動作確認

## 確認してほしいこと

- 省略

2024-12-30 10:24 UTC, g-ohara commented
Atlas のチェックの解除もお願いします

2024-12-30 11:41 UTC, dyoshyy requested changes
まだスマホでコードを見ただけ。動作確認はしてない
こっちで見るとフォーマットがおかしい(インデントがズレてる)から、出来れば直して欲しいかも。goは標準でフォーマット機能があるから調べてみて。

2024-12-30 11:41 UTC, dyoshyy commented on migrations/2_create_records.up.sql
> +  "is_red" boolean NULL,
migrationファイルは、migrateするためのものなので、過去のものは書き換えません。
モデルやアプリケーションロジックに変更があったら、それに伴って過去のデータも入っているテーブルを変更しなきゃいけない。そのときに実行するSQLをmigrationファイルにかきます。

2024-12-30 23:11 UTC, g-ohara commented
- フォーマットのずれを修正
- マイグレーションファイルの変更を削除
  - この辺の修正よくわからないので頼みます

2025-01-01 04:22 UTC, dyoshyy approved these changes

2025-01-01 05:28 UTC, merged